BACKUP_IGNORE_HEAD:
- __p
- .
BACKUP_IGNORE_KEY:
- log
- logfile
- dynamics_reward_models
- d4rl_dataset_converted
- ope_policy
- pretrained
BACKUP_IGNORE_TAIL:
- .tar
- egg-info
BASE_PATH: null
LOG_DIR_BACKING_NAME: offlinerl_log_0917
LOG_FOLDER_NAME: logfile
LOG_FOLDER_NAME_BK: logfile_bk
MAIN_MACHINE_IP:
- 172.16.15.99
MAIN_MACHINE_LOG_PATH: /mnt/FREENAS/ai/AlgDept/pdocker_logs/offlinerl_log_0917
MAIN_MACHINE_PASSWD: luofanming
MAIN_MACHINE_PORT:
- 22
MAIN_MACHINE_USER: luofanming
WORKSPACE_PATH: /home/luofm/Data
