BACKUP_IGNORE_HEAD:
- __p
- .
BACKUP_IGNORE_KEY:
- log
- logfile
- dynamics_reward_models
- d4rl_dataset_converted
- ope_policy
- pretrained
BACKUP_IGNORE_TAIL:
- .tar
- egg-info
BASE_PATH: null
LOG_DIR_BACKING_NAME: offlineRL
LOG_FOLDER_NAME: logfile
LOG_FOLDER_NAME_BK: logfile_bk
MAIN_MACHINE_IP:
- 192.168.1.1
MAIN_MACHINE_LOG_PATH: /path/to/remote/log
MAIN_MACHINE_PASSWD: user_name
MAIN_MACHINE_PORT:
- 22
MAIN_MACHINE_USER: user_name
WORKSPACE_PATH: /path/to/remote/log
